-- Official Seedling Scenarios Schema and Seed Data
CREATE TABLE IF NOT EXISTS scenarios (
  id TEXT PRIMARY KEY,
  key TEXT NOT NULL,
  engine_category TEXT NOT NULL DEFAULT 'Governance',
  governance_event TEXT NOT NULL,
  trigger TEXT NOT NULL DEFAULT '',
  audience TEXT NOT NULL DEFAULT '',
  communication_objective TEXT NOT NULL DEFAULT '',
  desired_outcome TEXT NOT NULL DEFAULT '',
  push_subject TEXT NOT NULL DEFAULT '',
  push_body TEXT NOT NULL DEFAULT '',
  email_subject TEXT NOT NULL DEFAULT '',
  email_body TEXT NOT NULL DEFAULT '',
  in_app_experience TEXT NOT NULL DEFAULT '',
  cta TEXT NOT NULL DEFAULT '',
  comments TEXT DEFAULT '',
  status TEXT NOT NULL DEFAULT 'TO DO',
  priority TEXT NOT NULL DEFAULT 'Medium',
  environment TEXT NOT NULL DEFAULT 'STAGING',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS engine_sheets (
  engine_category TEXT PRIMARY KEY,
  sheet_name TEXT NOT NULL,
  sheet_url TEXT NOT NULL,
  csv_export_url TEXT NOT NULL,
  enabled INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

INSERT OR REPLACE INTO engine_sheets VALUES
('Governance', 'Governance Content Sheet', 'https://docs.google.com/spreadsheets/d/1WQP9fY_pMUqZG28TX8gGSDL2vtb58ZAP/edit?usp=sharing&ouid=102314279700789110504&rtpof=true&sd=true', 'https://docs.google.com/spreadsheets/d/1WQP9fY_pMUqZG28TX8gGSDL2vtb58ZAP/export?format=csv', 1, datetime('now'), datetime('now')),
('Contribution', 'Contribution Content Sheet', 'https://docs.google.com/spreadsheets/d/1AtbvUxwJMRP4C4HxWFtPqEFnsx_EsocC/edit?usp=sharing&ouid=102314279700789110504&rtpof=true&sd=true', 'https://docs.google.com/spreadsheets/d/1AtbvUxwJMRP4C4HxWFtPqEFnsx_EsocC/export?format=csv', 1, datetime('now'), datetime('now'));

DELETE FROM scenarios;

INSERT INTO scenarios (id, key, engine_category, governance_event, trigger, audience, communication_objective, desired_outcome, push_subject, push_body, email_subject, email_body, in_app_experience, cta, status, priority, environment, created_at, updated_at) VALUES ('gov-1', 'GOV-1', 'Governance', 'Seedling Submitted for Review', 'Seedling Submitted', 'Sponsor, Co-Sponsors', 'Acknowledge submission', 'Review Seedling', 'Your Seedling is in review', 'Your Seedling is in Review', 'Your Seedling Is in Review', 'Thanks for submitting your Seedling! Our team is reviewing it now, and we''ll let you know as soon as it''s ready to go live.  BOX: View Status', 'Thanks! Your Seedling has been submitted for review -- once we have completed our review we''ll let you know!', 'take user to Seedling review status', 'TO DO', 'Medium', 'STAGING', datetime('now'), datetime('now'));
INSERT INTO scenarios (id, key, engine_category, governance_event, trigger, audience, communication_objective, desired_outcome, push_subject, push_body, email_subject, email_body, in_app_experience, cta, status, priority, environment, created_at, updated_at) VALUES ('gov-2', 'GOV-2', 'Governance', 'Seedling Approved', 'Seedling Approved', 'Sponsor, Co-Sponsors', 'Acknowledge Acceptance', 'Post Seedling', 'You''re live! 🎉', 'Congratulations -- your Seedling is Live!', 'You''re Live! 🎉', 'Great news -- your Seedling has been approved and is now live on Seedling. Now''s the time to start sharing it with your community and inviting support.  BOX: Share Your Seedling', 'Your Seedling has been approved and is now live on Seedling. Time to start sharing it with your community.  BOX: Share', 'take user directly to Seedling', 'TO DO', 'Medium', 'STAGING', datetime('now'), datetime('now'));
INSERT INTO scenarios (id, key, engine_category, governance_event, trigger, audience, communication_objective, desired_outcome, push_subject, push_body, email_subject, email_body, in_app_experience, cta, status, priority, environment, created_at, updated_at) VALUES ('gov-3', 'GOV-3', 'Governance', 'Seedling Rejected', 'Seedling Rejected', 'Sponsor, Co-Sponsors', 'Explain decision', 'Modify Seedling', 'Your Seedling needs a change', 'We couldn''t publish your Seedling -- Here''s why', 'Your Seedling Needs a Change', 'We weren''t able to publish your Seedling because it doesn''t currently meet our community guidelines. Review the reason we''ve provided, make the needed changes, and reach out to support if you have questions.  BOX: Edit Seedling', 'Your Seedling doesn''t meet our community guidelines. Review the reason provided and contact support if you have questions.', 'take user to Seedling edit screen with rejection reason', 'TO DO', 'Medium', 'STAGING', datetime('now'), datetime('now'));
INSERT INTO scenarios (id, key, engine_category, governance_event, trigger, audience, communication_objective, desired_outcome, push_subject, push_body, email_subject, email_body, in_app_experience, cta, status, priority, environment, created_at, updated_at) VALUES ('gov-4', 'GOV-4', 'Governance', 'Comment Reported', 'Comment Flagged by user', 'Reporter', 'Acknowledge report', 'Review Comment', 'Thanks for the report', 'Thank you for reporting a Seedling comment', 'Thanks for the Report', 'Thanks for helping keep Seedling welcoming. We''ll review the comment you reported, and if it merits removal, we''ll take care of it.', 'Thanks for helping keep Seedling welcoming. We''ll review the reported comment and if it merits removal we will do so.', 'confirm in place, no navigation required', 'TO DO', 'Medium', 'STAGING', datetime('now'), datetime('now'));
INSERT INTO scenarios (id, key, engine_category, governance_event, trigger, audience, communication_objective, desired_outcome, push_subject, push_body, email_subject, email_body, in_app_experience, cta, status, priority, environment, created_at, updated_at) VALUES ('gov-5', 'GOV-5', 'Governance', 'Comment Removed', 'Comment Removed', 'Commenter', 'Notify author', 'Comment removed', 'A comment was removed', 'One of your comments has been removed.', 'A Comment Was Removed', 'One of your comments has been removed because it violated our Community Guidelines. Take a look at our guidelines if you have questions.  BOX: View Guidelines', 'We removed one of your comments because it violated our Community Guidelines.', 'take user to Community Guidelines', 'TO DO', 'Medium', 'STAGING', datetime('now'), datetime('now'));
INSERT INTO scenarios (id, key, engine_category, governance_event, trigger, audience, communication_objective, desired_outcome, push_subject, push_body, email_subject, email_body, in_app_experience, cta, status, priority, environment, created_at, updated_at) VALUES ('gov-6', 'GOV-6', 'Governance', 'Comment Removed', 'Comment Removed', 'Reporter', 'Close the loop on report', 'Confirm resolution', 'Update on your report', 'Thanks for helping keep Seedling welcoming.', 'Update on Your Report', 'Thanks for helping keep Seedling welcoming. The comment you reported has been removed for violating our Community Guidelines.', 'The comment you reported has been removed for violating our Community Guidelines.', 'confirm in place, no navigation required', 'TO DO', 'Medium', 'STAGING', datetime('now'), datetime('now'));
INSERT INTO scenarios (id, key, engine_category, governance_event, trigger, audience, communication_objective, desired_outcome, push_subject, push_body, email_subject, email_body, in_app_experience, cta, status, priority, environment, created_at, updated_at) VALUES ('contrib-1', 'CONTRIB-1', 'Contribution', 'Donation Made via Credit/Debit Card', 'Donor makes donation', 'Donor', 'Thank donor', 'Positive moment', 'Thank you! 💚', 'Your donation moved (Seedling) one step closer to its goal -- thank you!', 'Thank You! 💚', 'Thank you! Your donation moved (Seedling) one step closer to its goal. Every gift counts, and yours just made a real difference.  BOX: View Donation', 'Your donation is complete -- (Seedling) is one step closer to its goal. Thank you!', 'take user directly to Seedling', 'TO DO', 'Medium', 'STAGING', datetime('now'), datetime('now'));
INSERT INTO scenarios (id, key, engine_category, governance_event, trigger, audience, communication_objective, desired_outcome, push_subject, push_body, email_subject, email_body, in_app_experience, cta, status, priority, environment, created_at, updated_at) VALUES ('contrib-2', 'CONTRIB-2', 'Contribution', 'ACH Donation Confirmed', 'Funds settled', 'Donor', 'Build trust', 'Retain confidence', 'Your ACH donation is confirmed ✅', 'Your ACH donation has been confirmed.', 'Your ACH Donation Is Confirmed ✅', 'Your ACH payment has fully processed and your donation is complete. Thank you for growing good.  BOX: View Donation', 'Your ACH payment has fully processed and your donation is complete.', 'take user to donation details', 'TO DO', 'Medium', 'STAGING', datetime('now'), datetime('now'));
INSERT INTO scenarios (id, key, engine_category, governance_event, trigger, audience, communication_objective, desired_outcome, push_subject, push_body, email_subject, email_body, in_app_experience, cta, status, priority, environment, created_at, updated_at) VALUES ('contrib-3', 'CONTRIB-3', 'Contribution', 'ACH Donation Failed', 'Payment declined', 'Donor', 'Resolve issue', 'Retry donation', 'We hit a snag with your donation', 'We couldn''t process your ACH donation.', 'We Hit a Snag With Your Donation', 'We weren''t able to process your ACH donation. Please update your payment method or try again so your gift can go through.  BOX: Update Payment', 'Your ACH payment didn''t go through -- please update your payment method or try again.', 'take user to payment method update screen', 'TO DO', 'Medium', 'STAGING', datetime('now'), datetime('now'));
INSERT INTO scenarios (id, key, engine_category, governance_event, trigger, audience, communication_objective, desired_outcome, push_subject, push_body, email_subject, email_body, in_app_experience, cta, status, priority, environment, created_at, updated_at) VALUES ('contrib-4', 'CONTRIB-4', 'Contribution', 'ACH Donation Pending', 'ACH or delayed payment', 'Donor', 'Set expectations', 'Await settlement', 'Your donation is on its way', 'Your ACH donation is being processed.', 'Your Donation Is on Its Way', 'Your ACH payment is on its way. We''ll let you know as soon as it''s confirmed -- no action needed in the meantime.  BOX: View Status', 'Your ACH payment is on its way. We''ll let you know as soon as it''s confirmed.', 'take user to donation status', 'TO DO', 'Medium', 'STAGING', datetime('now'), datetime('now'));
INSERT INTO scenarios (id, key, engine_category, governance_event, trigger, audience, communication_objective, desired_outcome, push_subject, push_body, email_subject, email_body, in_app_experience, cta, status, priority, environment, created_at, updated_at) VALUES ('contrib-5', 'CONTRIB-5', 'Contribution', 'Donation Receipt Available', 'Receipt generated', 'Donor', 'Provide documentation', 'Download receipt', 'Your receipt is ready 🧾', 'Your donation receipt is ready.', 'Your Receipt Is Ready 🧾', 'Your donation receipt is ready whenever you need it. Download or email it for your records anytime.  BOX: View Receipt', 'Download or email your official donation receipt anytime.  BOX: View Receipt', 'take user to donation receipt', 'TO DO', 'Medium', 'STAGING', datetime('now'), datetime('now'));
INSERT INTO scenarios (id, key, engine_category, governance_event, trigger, audience, communication_objective, desired_outcome, push_subject, push_body, email_subject, email_body, in_app_experience, cta, status, priority, environment, created_at, updated_at) VALUES ('contrib-6', 'CONTRIB-6', 'Contribution', 'GreenHouse Auto-Reload', 'Automatic funding', 'User', 'Maintain balance', 'Continue giving', 'Your GreenHouse is topped up', 'Your GreenHouse was automatically refilled.', 'Your GreenHouse Is Topped Up', 'Your GreenHouse balance has been automatically replenished, so you''re ready for your next act of generosity whenever inspiration strikes.  BOX: View GreenHouse', 'Your GreenHouse balance has been replenished so you''re ready for your next act of generosity.', 'take user to GreenHouse balance', 'TO DO', 'Medium', 'STAGING', datetime('now'), datetime('now'));
INSERT INTO scenarios (id, key, engine_category, governance_event, trigger, audience, communication_objective, desired_outcome, push_subject, push_body, email_subject, email_body, in_app_experience, cta, status, priority, environment, created_at, updated_at) VALUES ('contrib-7', 'CONTRIB-7', 'Contribution', 'GreenHouse Auto-Reload Failed', 'Auto reload unsuccessful', 'User', 'Resolve payment', 'Update funding source', 'We couldn''t refill your GreenHouse', 'We couldn''t refill your GreenHouse.', 'We Couldn''t Refill Your GreenHouse', 'Your GreenHouse auto-reload didn''t go through. Update your funding source to keep your GreenHouse topped up and ready to give.  BOX: Update Funding Source', 'Your GreenHouse auto-reload didn''t go through. Update your funding source to keep your GreenHouse topped up.  BOX: Update Funding Source', 'take user to GreenHouse reload process', 'TO DO', 'Medium', 'STAGING', datetime('now'), datetime('now'));
INSERT INTO scenarios (id, key, engine_category, governance_event, trigger, audience, communication_objective, desired_outcome, push_subject, push_body, email_subject, email_body, in_app_experience, cta, status, priority, environment, created_at, updated_at) VALUES ('contrib-8', 'CONTRIB-8', 'Contribution', 'GreenHouse Deposit Added', 'Funds deposited', 'User', 'Confirm balance', 'Use GreenHouse', 'Funds added! 💰', 'You''ve added funds to your GreenHouse.', 'Funds Added! 💰', 'Your funds have been added to your GreenHouse and are ready to donate whenever inspiration strikes.  BOX: View GreenHouse', 'Your funds have been added to your GreenHouse and are ready to donate whenever inspiration strikes.', 'take user to GreenHouse', 'TO DO', 'Medium', 'STAGING', datetime('now'), datetime('now'));
INSERT INTO scenarios (id, key, engine_category, governance_event, trigger, audience, communication_objective, desired_outcome, push_subject, push_body, email_subject, email_body, in_app_experience, cta, status, priority, environment, created_at, updated_at) VALUES ('contrib-9', 'CONTRIB-9', 'Contribution', 'GreenHouse Donation Made', 'Donation from balance', 'User', 'Confirm transaction', 'Continue giving', 'Donation sent from your GreenHouse', 'Your donation was sent from your GreenHouse.', 'Donation Sent From Your GreenHouse', 'Your donation was sent using your GreenHouse balance. Thank you for growing good.  BOX: View Donation', 'Your donation was sent using your GreenHouse balance. Thank you for Growing Good.', 'take user directly to Seedling', 'TO DO', 'Medium', 'STAGING', datetime('now'), datetime('now'));
INSERT INTO scenarios (id, key, engine_category, governance_event, trigger, audience, communication_objective, desired_outcome, push_subject, push_body, email_subject, email_body, in_app_experience, cta, status, priority, environment, created_at, updated_at) VALUES ('contrib-10', 'CONTRIB-10', 'Contribution', 'Payment Method Added', 'New payment method', 'User', 'Confirm setup', 'Complete donation', 'Payment method added ✅', 'Payment method added successfully.', 'Payment Method Added ✅', 'Your new payment method has been added successfully and is ready for future donations.  BOX: View Payment Methods', 'Your new payment method is ready for future donations.', 'take user to payment methods', 'TO DO', 'Medium', 'STAGING', datetime('now'), datetime('now'));
INSERT INTO scenarios (id, key, engine_category, governance_event, trigger, audience, communication_objective, desired_outcome, push_subject, push_body, email_subject, email_body, in_app_experience, cta, status, priority, environment, created_at, updated_at) VALUES ('contrib-11', 'CONTRIB-11', 'Contribution', 'Payment Method Expiring', 'Card nearing expiration', 'Donor', 'Prevent failed payments', 'Update payment', 'Your card is expiring soon', 'Your payment method expires soon.', 'Your Card Is Expiring Soon', 'Your payment method expires soon. Update it now to avoid any interruption to your giving.  BOX: Update Payment', 'Update your payment information to avoid interrupted giving.', 'take user to payment method update screen', 'TO DO', 'Medium', 'STAGING', datetime('now'), datetime('now'));
INSERT INTO scenarios (id, key, engine_category, governance_event, trigger, audience, communication_objective, desired_outcome, push_subject, push_body, email_subject, email_body, in_app_experience, cta, status, priority, environment, created_at, updated_at) VALUES ('contrib-12', 'CONTRIB-12', 'Contribution', 'Payment Method Preferences Updated', 'Giving settings changed', 'Donor', 'Confirm preferences', 'Maintain trust', 'Preferences updated', 'Payment preferences updated.', 'Preferences Updated', 'Your preferred payment settings have been saved exactly the way you wanted.  BOX: View Preferences', 'Your preferred payment settings have been saved.', 'take user to payment preferences', 'TO DO', 'Medium', 'STAGING', datetime('now'), datetime('now'));
INSERT INTO scenarios (id, key, engine_category, governance_event, trigger, audience, communication_objective, desired_outcome, push_subject, push_body, email_subject, email_body, in_app_experience, cta, status, priority, environment, created_at, updated_at) VALUES ('contrib-13', 'CONTRIB-13', 'Contribution', 'Payment Method Updated', 'Payment details changed', 'Donor', 'Confirm update', 'Maintain continuity', 'Payment method updated', 'Your payment method has been updated.', 'Payment Method Updated', 'Your payment method has been updated. Your changes have been saved and are ready to use.  BOX: View Payment Methods', 'Your changes have been saved and are ready to use.', 'take user to payment methods', 'TO DO', 'Medium', 'STAGING', datetime('now'), datetime('now'));
INSERT INTO scenarios (id, key, engine_category, governance_event, trigger, audience, communication_objective, desired_outcome, push_subject, push_body, email_subject, email_body, in_app_experience, cta, status, priority, environment, created_at, updated_at) VALUES ('contrib-14', 'CONTRIB-14', 'Contribution', 'Receipt Downloaded', 'Receipt accessed', 'Donor', 'Confirm access', 'Retain records', 'Receipt downloaded', 'Receipt downloaded.', 'Receipt Downloaded', 'Your donation receipt has been downloaded successfully and is ready for your records.', 'Your donation receipt has been downloaded successfully.', 'confirm in place, no navigation required', 'TO DO', 'Medium', 'STAGING', datetime('now'), datetime('now'));
